CREATE TABLE SINGER (
	ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(60) NOT NULL,
	LAST_NAME VARCHAR(40) NOT NULL,
	BIRTH_DATE DATE,
	UNIQUE(FIRST_NAME, LAST_NAME)
);

CREATE TABLE ALBUM (
	ID SERIAL PRIMARY KEY,
	SINGER_ID INT NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	RELEASE_DATE DATE,
	UNIQUE(SINGER_ID, TITLE),
	CONSTRAINT FK_ALBUM FOREIGN KEY (SINGER_ID) REFERENCES SINGER(ID)
);

CREATE FUNCTION getFirstNameById(in_id INT)
RETURNS VARCHAR(60)
LANGUAGE SQL
AS $$
	SELECT first_name FROM singer WHERE id = in_id
$$;
